theme = "archie-network"
baseURL = "http://192.168.1.82:1313/"
languageCode = "en-us"
title = "/home/mackle/emporium"
copyright = "© Stuart Mackle"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
mode = "auto"
subtitle = "Technical musings and other disorganised nonsense"
useCDN=false

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mackles"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/stuart-mackle-5b2055105/"

